import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // The Journey — Material 3-style token set (matches the Stitch design export exactly)
        surface: '#fbf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#fbf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ef',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-variant': '#e4e2de',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#414844',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f0ed',
        outline: '#717973',
        'outline-variant': '#c1c8c2',
        'surface-tint': '#3f6653',
        primary: '#012d1d',
        'on-primary': '#ffffff',
        'primary-container': '#1b4332',
        'on-primary-container': '#86af99',
        'inverse-primary': '#a5d0b9',
        'primary-fixed': '#c1ecd4',
        'primary-fixed-dim': '#a5d0b9',
        'on-primary-fixed': '#002114',
        'on-primary-fixed-variant': '#274e3d',
        secondary: '#4e644b',
        'on-secondary': '#ffffff',
        'secondary-container': '#d0eaca',
        'on-secondary-container': '#546a51',
        'secondary-fixed': '#d0eaca',
        'secondary-fixed-dim': '#b5cdaf',
        'on-secondary-fixed': '#0c200c',
        'on-secondary-fixed-variant': '#374c35',
        tertiary: '#1e291d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#333f32',
        'on-tertiary-container': '#9daa99',
        'tertiary-fixed': '#d9e6d3',
        'tertiary-fixed-dim': '#bdcab8',
        'on-tertiary-fixed': '#131e13',
        'on-tertiary-fixed-variant': '#3e4a3c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f5',
        'on-background': '#1b1c1a',
        // Accent — muted ochre, used sparingly (special moments, highlights)
        accent: '#d4a373',
        'on-accent': '#3a2a14',

        // Legacy aliases kept so existing component classes keep working while
        // they're migrated — mapped onto the new palette above, not the old one.
        cream: {
          50: '#fbf9f5',
          100: '#f5f3ef',
          200: '#efeeea',
          300: '#e4e2de',
          400: '#c1c8c2',
        },
        forest: {
          50: '#f1f6f2',
          100: '#dfebe2',
          200: '#c1ecd4',
          300: '#a5d0b9',
          400: '#6e9c7c',
          500: '#3f6653',
          600: '#274e3d',
          700: '#1b4332',
          800: '#012d1d',
          900: '#002114',
        },
        stone: {
          50: '#fbf9f5',
          100: '#efeeea',
          200: '#e4e2de',
          300: '#c1c8c2',
          400: '#717973',
          500: '#414844',
          600: '#30312e',
          700: '#1b1c1a',
          800: '#1b1c1a',
          900: '#1b1c1a',
        },
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-jakarta)', 'var(--font-inter)', 'system-ui', 'sans-serif'],
        serif: ['var(--font-caslon)', 'Georgia', 'serif'],
        caslon: ['var(--font-caslon)', 'Georgia', 'serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        gutter: '24px',
        'container-max': '1200px',
        'margin-mobile': '24px',
        'margin-desktop': '64px',
        unit: '8px',
        'stack-sm': '16px',
        'stack-md': '32px',
        'stack-lg': '64px',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      boxShadow: {
        card: '0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)',
        elevated: '0 4px 12px -2px rgb(0 0 0 / 0.08), 0 2px 6px -2px rgb(0 0 0 / 0.06)',
        dropdown: '0 8px 24px -4px rgb(0 0 0 / 0.12), 0 4px 12px -4px rgb(0 0 0 / 0.08)',
        soft: '0 24px 48px rgba(1, 45, 29, 0.04)',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(14px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        draw: {
          '0%': { strokeDashoffset: '1200' },
          '100%': { strokeDashoffset: '0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.7s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in': 'fade-in 0.8s ease-out both',
        draw: 'draw 2.2s cubic-bezier(0.65, 0, 0.35, 1) forwards',
        float: 'float 5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}

export default config
